spring:
  datasource:
    url: jdbc:mysql://77.77.77.110/login
    username: tester01
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret-key: abcdefghijklmnopqrstuvwxyz0123456789
  token:
    expired-time-ms: 300000